// Generated by Sophon Schema. Do not edit manually!
import io, { Socket } from 'socket.io-client';


export interface Person {
  name: string;
  age: number;
}

class SocketClient {
  constructor(public socket: Socket) {}

  call(event: string, ...args: any[]): any {
    return new Promise((resolve) => {
      this.socket.emit(event, ...args, resolve);
    });
  }

  subscribe(ev: string, handler: any) {
    this.socket.on(ev, handler);
    return () => { this.socket.off(ev, handler); };
  }
}

class MainClient {
  constructor(private socket: SocketClient) {}
  adder(x: number, y: number): Promise<number> {
    return this.socket.call('Main/adder', x, y);
  }
  hello(p: Person): Promise<string> {
    return this.socket.call('Main/hello', p);
  }

  ping(handler: (n: number) => void) {
    return this.socket.subscribe('Main/ping', handler);
  }
}

export function createClient(url: string) {
  return new Promise<{
    main: MainClient;
  }>((resolve) => {
    const socket = io(url);

    socket.once('connect', () => {
      const socketClient = new SocketClient(socket);
      resolve({
        main: new MainClient(socketClient),
      });
    });
  });
}
