// Generated by Sophon Schema. Do not edit manually!
import { SophonInstance, SenderCore } from '@sophonjs/server';


export interface Person {
  name: string;
  age: number;
}

// Services

export class MainServiceSender {
  constructor(private sender: SenderCore, private room: string) {}
  ping(n: number) {
    this.sender.emit(this.room, 'ping', n);
  }
}

export abstract class AbstractMainService {
  readonly NAMESPACE = 'Main';
  static readonly SENDER = MainServiceSender;
  readonly $!: (room: string) => MainServiceSender;
  abstract child: AbstractChildService;
  abstract adder(ctx: SophonInstance, x: number, y: number): Promise<number>;
  abstract hello(ctx: SophonInstance, p: Person): Promise<string>;
}

export class ChildServiceSender {
  constructor(private sender: SenderCore, private room: string) {}
  pong(s: string) {
    this.sender.emit(this.room, 'child/pong', s);
  }
}

export abstract class AbstractChildService {
  readonly NAMESPACE = 'Child';
  static readonly SENDER = ChildServiceSender;
  readonly $!: (room: string) => ChildServiceSender;
  
  abstract hello(ctx: SophonInstance): Promise<string>;
}
